name: Lint Code

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'  # Adjust version as per your project's requirement

      - name: Install Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Specify any additional languages or linters you want to include
          # EXCLUDED_RULES: 'eslint,bundler-audit'

      # Add more steps as needed, such as building and testing your C# application
